#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
# mofidfiyed by n.reibel@tastatur.de
#
# SPDX-License-Identifier:	GPL-2.0+
#

ifndef	CONFIG_SPL_BUILD
obj-y	:= mx23_huk_flexxgui.o
else
obj-y	:= spl_boot.o
endif
